#!/usr/bin/env python3
"""Merge Kondratiy Andreevich branch into sustatov_tree_data.json."""
import json
from pathlib import Path

ROOT = Path(__file__).parent
data = json.loads((ROOT / "sustatov_tree_data.json").read_text(encoding="utf-8"))
by_id = {n["id"]: n for n in data}

VGD140 = "https://forum.vgd.ru/2339/86148/140.htm"
VGD1807 = "https://forum.vgd.ru/post/2339/86148/p2995932.htm"
VGD1835 = "https://forum.vgd.ru/post/2339/86148/p2995932.htm"
VGD1851 = "https://forum.vgd.ru/post/2339/86148/p2879430.htm"
VGD1855 = "https://forum.vgd.ru/post/2339/86148/p2879430.htm"

NEW_AND_UPDATES = [
    {
        "id": "side-004",
        "name": "Кондратий Андреевич Сустатов",
        "born": "1765",
        "died": "1847",
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": ["sust-ap-1770", "sust-darya-ap"],
        "spouseIds": ["side-004a"],
        "childIds": ["side-005", "side-006", "side-007", "side-004b", "side-004c"],
        "status": "confirmed",
        "role": "side",
        "gen": 2,
        "sources": [VGD140, VGD1807, "ревизия 1858, д.21"],
        "notes": "Брак 08.11.1807 с Анной Филиповной; отец — Андрей Петрович (док. метрики)",
    },
    {
        "id": "side-004a",
        "name": "Анна Филипповна",
        "born": "~1798",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": [],
        "spouseIds": ["side-004"],
        "childIds": ["side-005", "side-006", "side-007", "side-004b", "side-004c"],
        "status": "confirmed",
        "role": "inlaw",
        "gen": 2,
        "sources": [VGD1807, VGD140],
        "notes": "Дочь Филиппа Михайловича; рев.1858 — 60 лет",
    },
    {
        "id": "side-004b",
        "name": "Мавра Кондратьевна",
        "born": "~1840",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": ["side-004", "side-004a"],
        "spouseIds": [],
        "childIds": [],
        "status": "confirmed",
        "role": "side",
        "gen": 3,
        "sources": [VGD140],
        "notes": "Рев.1858 — 18 лет; дальнейшие потомки NOT FOUND",
    },
    {
        "id": "side-004c",
        "name": "Аграфена Кондратьевна",
        "born": "~1845",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": ["side-004", "side-004a"],
        "spouseIds": ["side-004c-sp"],
        "childIds": ["side-004c-ch"],
        "status": "confirmed",
        "role": "side",
        "gen": 3,
        "sources": [VGD140],
        "notes": "Рев.1858 — 13/37 лет; жена Ефима Ивановича",
    },
    {
        "id": "side-004c-sp",
        "name": "Ефим Иванович",
        "born": "~1830",
        "died": None,
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": [],
        "spouseIds": ["side-004c"],
        "childIds": ["side-004c-ch"],
        "status": "confirmed",
        "role": "inlaw",
        "gen": 3,
        "sources": [VGD140],
        "notes": "",
    },
    {
        "id": "side-004c-ch",
        "name": "Иван Ефимович",
        "born": "~1857",
        "died": None,
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": ["side-004c-sp", "side-004c"],
        "spouseIds": [],
        "childIds": [],
        "status": "probable",
        "role": "side",
        "gen": 4,
        "sources": [VGD140],
        "notes": "Рев.1858 — 1 год; потомки до 2026 NOT FOUND",
    },
    {
        "id": "side-005",
        "name": "Аверьян Кондратьевич Сустатов",
        "born": "~1827",
        "died": None,
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": ["side-004", "side-004a"],
        "spouseIds": ["side-005a"],
        "childIds": ["side-005b"],
        "status": "confirmed",
        "role": "side",
        "gen": 3,
        "sources": [VGD140, VGD1835],
        "notes": "Брак 08.11.1835 + Дарья Анисимовна; рев.1858 — 31 год",
    },
    {
        "id": "side-005a",
        "name": "Дарья Анисимовна",
        "born": "~1823",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": [],
        "spouseIds": ["side-005"],
        "childIds": ["side-005b"],
        "status": "confirmed",
        "role": "inlaw",
        "gen": 3,
        "sources": [VGD140, VGD1835],
        "notes": "Рев.1858 — 35 лет",
    },
    {
        "id": "side-005b",
        "name": "Екатерина Аверьяновна",
        "born": "~1844",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": ["side-005", "side-005a"],
        "spouseIds": ["side-005c"],
        "childIds": ["side-005d"],
        "status": "confirmed",
        "role": "side",
        "gen": 4,
        "sources": [VGD140, VGD1855],
        "notes": "Брак 09.11.1855; в метрике: «дочь Аверкия Кондратьевича» (= Аверьян)",
    },
    {
        "id": "side-005c",
        "name": "Иван Евдокимович",
        "born": "~1844",
        "died": None,
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": [],
        "spouseIds": ["side-005b"],
        "childIds": ["side-005d"],
        "status": "confirmed",
        "role": "inlaw",
        "gen": 4,
        "sources": [VGD140, VGD1855],
        "notes": "Рев.1858 — 20 лет; муж Екатерины Аверьяновны",
    },
    {
        "id": "side-005d",
        "name": "Наталья Ивановна",
        "born": "~1858",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": ["side-005c", "side-005b"],
        "spouseIds": [],
        "childIds": [],
        "status": "probable",
        "role": "side",
        "gen": 5,
        "sources": [VGD140],
        "notes": "Рев.1858 — младенец (½); потомки до 2026 NOT FOUND в открытых источниках",
    },
    {
        "id": "side-006",
        "name": "Максим Кондратьевич Сустатов",
        "born": "~1835",
        "died": "1840",
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": ["side-004", "side-004a"],
        "spouseIds": [],
        "childIds": [],
        "status": "confirmed",
        "role": "side",
        "gen": 3,
        "sources": [VGD140],
        "notes": "Рев.1858: «5 лет / умер в 1840 г.» — без потомков",
    },
    {
        "id": "side-007",
        "name": "Степан Кондратьевич Сустатов",
        "born": "~1841",
        "died": None,
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": ["side-004", "side-004a"],
        "spouseIds": ["side-007a"],
        "childIds": ["side-007b"],
        "status": "confirmed",
        "role": "side",
        "gen": 3,
        "sources": [VGD140, VGD1851],
        "notes": "Брак 09.11.1851; рекрут с 1855 г.; рев.1858 — 17 лет (р.~1841). ⚠️ Метрика 1851 указывает 18 л. — возможна погрешность или тёзка",
    },
    {
        "id": "side-007a",
        "name": "Анастасия Антоновна",
        "born": "~1835",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": [],
        "spouseIds": ["side-007"],
        "childIds": ["side-007b"],
        "status": "confirmed",
        "role": "inlaw",
        "gen": 3,
        "sources": [VGD1851, VGD140],
        "notes": "Дочь Антона Григорьевича; рев.1858 — 23 года",
    },
    {
        "id": "side-007b",
        "name": "Арина Степановна",
        "born": "~1826",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": ["side-007", "side-007a"],
        "spouseIds": [],
        "childIds": [],
        "status": "probable",
        "role": "side",
        "gen": 4,
        "sources": [VGD140],
        "notes": "«Пlemянница Аверьяна» в рев.1858 (32 г.) — вероятно дочь Степана; потомки NOT FOUND",
    },
    {
        "id": "side-009",
        "name": "Василий Андреевич Сустатов",
        "born": "~1800",
        "died": None,
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": ["sust-ap-1770", "sust-darya-ap"],
        "spouseIds": ["side-009a"],
        "childIds": ["side-009b", "side-009c", "side-009d"],
        "status": "confirmed",
        "role": "side",
        "gen": 2,
        "sources": [VGD140],
        "notes": "Брат Кондратия Андреевича (не сын); рев.1858 — 58 лет",
    },
    {
        "id": "side-009a",
        "name": "Ульяна",
        "born": "~1819",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": [],
        "spouseIds": ["side-009"],
        "childIds": ["side-009b", "side-009c", "side-009d"],
        "status": "confirmed",
        "role": "inlaw",
        "gen": 2,
        "sources": [VGD140],
        "notes": "",
    },
    {
        "id": "side-009b",
        "name": "Аким Васильевич Сустатов",
        "born": "~1820",
        "died": None,
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": ["side-009", "side-009a"],
        "spouseIds": ["side-009e"],
        "childIds": ["side-009f", "side-009g"],
        "status": "confirmed",
        "role": "side",
        "gen": 3,
        "sources": [VGD140, "брак 09.11.1845"],
        "notes": "Рев.1858 — 38 лет",
    },
    {
        "id": "side-009c",
        "name": "Степан Васильевич Сустатов",
        "born": "~1835",
        "died": None,
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": ["side-009", "side-009a"],
        "spouseIds": ["side-009h"],
        "childIds": [],
        "status": "confirmed",
        "role": "side",
        "gen": 3,
        "sources": [VGD140, "брак 09.11.1845"],
        "notes": "Рекрут с 1853 г.; рев.1858 — 23 года",
    },
    {
        "id": "side-009d",
        "name": "Матрёна Васильевна",
        "born": "~1845",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": ["side-009", "side-009a"],
        "spouseIds": [],
        "childIds": [],
        "status": "confirmed",
        "role": "side",
        "gen": 3,
        "sources": [VGD140],
        "notes": "",
    },
    {
        "id": "side-009e",
        "name": "Арина Ильинична",
        "born": "~1821",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": [],
        "spouseIds": ["side-009b"],
        "childIds": ["side-009f", "side-009g"],
        "status": "confirmed",
        "role": "inlaw",
        "gen": 3,
        "sources": [VGD140],
        "notes": "",
    },
    {
        "id": "side-009f",
        "name": "Степан Акимович Сустатов",
        "born": "~1847",
        "died": None,
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": ["side-009b", "side-009e"],
        "spouseIds": [],
        "childIds": [],
        "status": "confirmed",
        "role": "side",
        "gen": 4,
        "sources": [VGD140],
        "notes": "Рев.1858 — 11/18 лет; потомки NOT FOUND",
    },
    {
        "id": "side-009g",
        "name": "Никита Акимович Сустатов",
        "born": "1855",
        "died": None,
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": ["side-009b", "side-009e"],
        "spouseIds": [],
        "childIds": [],
        "status": "confirmed",
        "role": "side",
        "gen": 4,
        "sources": [VGD140],
        "notes": "Р.1855; потомки NOT FOUND",
    },
    {
        "id": "side-009h",
        "name": "Анна Тимофеевна",
        "born": "~1835",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": [],
        "spouseIds": ["side-009c"],
        "childIds": [],
        "status": "confirmed",
        "role": "inlaw",
        "gen": 3,
        "sources": [VGD140],
        "notes": "",
    },
    {
        "id": "side-010",
        "name": "Лев Анисимович Сустатов",
        "born": "~1815",
        "died": "1843",
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": [],
        "spouseIds": ["side-010a"],
        "childIds": ["side-010b"],
        "status": "confirmed",
        "role": "side",
        "gen": 2,
        "sources": [VGD140, VGD1835],
        "notes": "Сын Анисима Михайловича (не Андрея Петровича); рев.1858 — †1843",
    },
    {
        "id": "side-010a",
        "name": "Акилина Евдокимовна",
        "born": "~1810",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": [],
        "spouseIds": ["side-010"],
        "childIds": ["side-010b"],
        "status": "confirmed",
        "role": "inlaw",
        "gen": 2,
        "sources": [VGD1835],
        "notes": "",
    },
    {
        "id": "side-010b",
        "name": "Пантелей Львович Сустатов",
        "born": "~1837",
        "died": "1840",
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": ["side-010", "side-010a"],
        "spouseIds": [],
        "childIds": [],
        "status": "confirmed",
        "role": "side",
        "gen": 3,
        "sources": [VGD140],
        "notes": "†1840; без потомков",
    },
    {
        "id": "side-010c",
        "name": "Василий Анисимович Сустатов",
        "born": "~1819",
        "died": None,
        "place": "Кошелиха",
        "sex": "M",
        "parentIds": [],
        "spouseIds": ["side-010d"],
        "childIds": [],
        "status": "confirmed",
        "role": "side",
        "gen": 2,
        "sources": [VGD140],
        "notes": "Брат Льва Анисимовича; рев.1858 — 39 лет",
    },
    {
        "id": "side-010d",
        "name": "Аксинья Егоровна",
        "born": "~1819",
        "died": None,
        "place": "Кошелиха",
        "sex": "F",
        "parentIds": [],
        "spouseIds": ["side-010c"],
        "childIds": [],
        "status": "confirmed",
        "role": "inlaw",
        "gen": 2,
        "sources": [VGD140],
        "notes": "",
    },
]

# Update sust-ap-1770 children list
if "sust-ap-1770" in by_id:
    kids = set(by_id["sust-ap-1770"].get("childIds", []))
    kids.update(["side-004", "side-008", "side-009", "sust-ia-1793"])
    by_id["sust-ap-1770"]["childIds"] = sorted(kids)

for node in NEW_AND_UPDATES:
    by_id[node["id"]] = node

# Remove stale side-005 if only had empty childIds - already replaced
data = list(by_id.values())
data.sort(key=lambda n: (n.get("gen") or 99, n.get("name") or ""))

(ROOT / "sustatov_tree_data.json").write_text(
    json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8"
)
print(f"Merged Kondratiy branch: {len(data)} nodes total")
